### ISSUE TITLE
 Implement Perft Functionality for Move Generation

### ISSUE THREAD

**Issue by AadarshDubey** [fffelix-huang/Sonic#16]
The perft function can be added to the codebase to recursively count legal positions from a given chess position up to a specified depth. This addition aims to enhance the verification of move generation accuracy in the chess engine, ensuring that all potential moves are accounted for correctly.

**Comment by fffelix-huang** [comment]
Hi @AadarshDubey 

Thanks for the pull request. However, we already have a perft function under src/bench/perft.cpp
