### ISSUE TITLE
Improve UCI Loop Code for Enhanced Robustness and Usability in uci.cpp

### ISSUE THREAD

**Issue by Amansingh0807** [fffelix-huang/Sonic#20]
The UCI loop code in the Sonic chess engine requires improvements in several areas to enhance its robustness and user experience.

Issues Identified:

1. Thread Safety: The current implementation does not adequately manage thread safety when accessing shared resources during search operations.
2. Error Handling: Limited error handling for user commands and settings can lead to silent failures; clearer error messages are needed for invalid inputs.
3. Magic Numbers: The use of magic numbers (e.g., in moves_start) reduces code clarity; these should be replaced with named constants.
4. Command Suggestions: The Unknown Command response lacks helpful suggestions for available commands

 Improvements: (which i recently did)

1. Implemented thread synchronization mechanisms for shared resources.
2. Added validation checks and clear error messages for user inputs.
3. Used named constants to replace magic numbers for better readability.
4. Enhanced user feedback by providing available command options when an unknown command is entered.

**Comment by Ncode-93** [comment]
I think following improvements would be good:
**Thread Safety:** Introduced thread synchronization (using std::mutex for shared resource access).
**Error Handling:** Added clearer error messages for invalid inputs and command errors.
**Magic Numbers:** Replaced magic numbers with named constants for better readability.
**Command Suggestions:** Enhanced the response for unknown commands by listing available command options.
Your notions are welcomed.

**Comment by Amansingh0807** [comment]
> I think following improvements would be good: **Thread Safety:** Introduced thread synchronization (using std::mutex for shared resource access). **Error Handling:** Added clearer error messages for invalid inputs and command errors. **Magic Numbers:** Replaced magic numbers with named constants for better readability. **Command Suggestions:** Enhanced the response for unknown commands by listing available command options. Your notions are welcomed.






I have implemented the suggested improvements: in issue number #19 

Thread Safety: Added std::mutex to ensure proper synchronization of shared resources between threads, enhancing the stability in multi-threaded operations.
Error Handling: Improved error messages for invalid commands and inputs, making it clearer for users to debug issues.
Magic Numbers: Replaced hard-coded values with named constants to increase code readability and maintainability.
Command Suggestions: Enhanced the error response for unknown commands by listing valid alternatives, making the engine more user-friendly.
please review the changes !!
